'use strict';

export default {
  Actions : {
    CREATE: 'CREATE',
    CHANGE: 'CHANGE',
    UPDATE_BASICS: 'UPDATE_BASICS',
    ADD_BACKGROUND: 'ADD_BACKGROUND',
    SET_SIMPLE_DATA: 'SET_SIMPLE_DATA',
    SET_SIMPLE_LIST_DATA: 'SET_SIMPLE_LIST_DATA',
    SET_GENERAL_SKILL: 'SET_GENERAL_SKILL',
    ADD_SPECIALIST_SKILL: 'ADD_SPECIALIST_SKILL',
    SET_SPECIALIST_SKILL_RANK: 'SET_SPECIALIST_SKILL_RANK',
    ADD_COMBAT_STYLE: 'ADD_COMBAT_STYLE',
    SET_COMBAT_STYLE_RANK: 'SET_COMBAT_STYLE_RANK',
    SET_CREDO: "SET_CREDO"
  }
}
