'use strict';

export default {
  Actions : {
    CHANGE: 'CHANGE',
    UPDATE_BASICS: 'UPDATE_BASICS',
    ADD_BACKGROUND: 'ADD_BACKGROUND',
    SET_SIMPLE_DATA: 'SET_SIMPLE_DATA',
    ADD_COMBAT_STYLE: 'ADD_COMBAT_STYLE'
  }
}
